### PR TITLE
PFA guide

### PR DESCRIPTION
**Pull request by GreenWeegeeCantCode**
I added a PFA guide that contains how to install it, how to view 128 keys and patch pfa.
I tried to view the page but idk how to do that.

### CODE REVIEW

**Comment by GreenWeegeeCantCode** [comment]
Finally got pages to use mkdocs.
Screenshots:
image
image
image
image
image
image

**Comment by 6gh** [comment]
Nice guide! The guide will be added after I fix a few things like the images and a few typos. It's been added to the guide/pfa branch so that I can fix it up before publishing it. Thank you for contributing!

**Comment by GreenWeegeeCantCode** [comment]
thanks for merging this!
later ill check the fixed version when you add it to the site

**Comment by 6gh** [comment]
PFA guide has been added to the latest build! It is available at https://guides.blackmidi.wiki/Piano%20From%20Above/

I am planning to change the link to https://guides.blackmidi.wiki/PFA/ though in the future.

**Pull request merged**
