### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by PopoTheGamer**
Adding Black MIDI render informations, such as introducing both Zenith and UMP as Black MIDI renderer.

### CODE REVIEW

**Comment by PopoTheGamer** [comment]
Gonna replace it with newer one with the images

**Comment by GreenWeegeeCantCode** [comment]
no, zenith and ump should be seperate guides
and remove the render thing

**Comment by GreenWeegeeCantCode** [comment]
omnimidi and pfa patch are seperate guides

**Comment by GreenWeegeeCantCode** [comment]
just let me or snowy do it

**Pull request closed without merging**
